
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package jFlexCup.parser;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int Startparenthesis = 9;
  public static final int Not = 2;
  public static final int Biconditional = 7;
  public static final int Enter = 11;
  public static final int EOF = 0;
  public static final int Code = 3;
  public static final int Reverseconditional = 8;
  public static final int And = 4;
  public static final int Or = 5;
  public static final int Conditional = 6;
  public static final int error = 1;
  public static final int Stopparenthesis = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Not",
  "Code",
  "And",
  "Or",
  "Conditional",
  "Biconditional",
  "Reverseconditional",
  "Startparenthesis",
  "Stopparenthesis",
  "Enter"
  };
}

